// Maps archive posts (src/blogArchiveContent.js) to pictures in
// src/assets/blog. Generated by scripts/match-blog-images.mjs.
//
// The legacy /blog HTML pages held the real mapping in their <img> tags; that
// folder no longer exists, so these were matched on file name and title. Most
// are unambiguous, but the ones flagged CHECK below matched on weaker evidence
// — correct any of them by editing the entry, it is a plain object.

import imgWorldMyth from "./assets/blog/world-myth.jpg";
import imgEntrepreneurshipBengali from "./assets/blog/Entrepreneurship-Bengali.jpg";
import imgAIGaming from "./assets/blog/AI-gaming.jpg";
import imgAlien from "./assets/blog/alien.jpg";
import imgPitchDeckForYourStartup from "./assets/blog/pitch-deck-for-your-startup.jpg";
import imgLearn from "./assets/blog/learn.jpg";
import imgInnovation from "./assets/blog/innovation.jpg";
import imgBlockchainCrypto from "./assets/blog/blockchain-crypto.jpg";
import imgVirus from "./assets/blog/virus.jpg";
import imgDonthavetime from "./assets/blog/donthavetime.jpg";
import imgLuck from "./assets/blog/luck.jpg";
import imgCEO from "./assets/blog/CEO.jpg";
import imgBombleBee from "./assets/blog/bomble_bee.jpg";
import imgLimitedPartnerships from "./assets/blog/Limited-Partnerships.jpg";
import imgCulture from "./assets/blog/culture.jpg";
import imgWorldEconomyCoronaVirus from "./assets/blog/world-economy-corona-virus.jpg";
import imgDividingEquityAmongCoFo from "./assets/blog/Dividing-Equity-among-Co-fo.jpg";
import imgStartupEcosystemReset from "./assets/blog/startup-ecosystem-reset.jpg";
import imgEarthMagnetic from "./assets/blog/earth-magnetic.png";
import imgEconomyIndia from "./assets/blog/economy_India.jpg";
import imgENTREPRENEURSHIPEMPLOYMENT from "./assets/blog/ENTREPRENEURSHIP-EMPLOYMENT.png";
import imgArijitBhattacharyyaHappy from "./assets/blog/arijit-bhattacharyya-happy.jpg";
import imgVirusCorona from "./assets/blog/virus-corona.jpg";
import imgCEOFunding from "./assets/blog/CEO-funding.jpg";
import imgScalingStartups from "./assets/blog/scaling-startups.jpg";
import imgSpaceTravel from "./assets/blog/space-travel.jpg";
import imgHardWork from "./assets/blog/Hard-work.jpg";
import imgBlockchainInBanking from "./assets/blog/blockchain-in-banking.jpg";
import imgCosplay from "./assets/blog/cosplay.jpg";
import imgVentureCapital from "./assets/blog/venture-capital.jpg";
import imgEconomicTimes from "./assets/blog/economic-times.jpg";
import imgArijitPublicSpeaking from "./assets/blog/arijit-public-speaking.jpg";
import imgSuccessfullyContentWithY from "./assets/blog/Successfully-Content-with-Y.jpg";
import imgStartupSuccess from "./assets/blog/startup-success.jpg";
import imgSoloPrenure from "./assets/blog/solo-prenure.jpg";
import imgStartupEcosystem from "./assets/blog/startup-ecosystem.jpg";
import imgTimeTechnology from "./assets/blog/time-technology.png";
import imgStrategiesForEntrepreneur from "./assets/blog/Strategies-for-Entrepreneur.png";
import imgStartup from "./assets/blog/startup.jpg";
import imgAztechGods from "./assets/blog/aztech-gods.jpg";
import imgInternationalEntrepreneurs from "./assets/blog/International-entrepreneurs.jpg";
import imgStartupIdeaViable from "./assets/blog/startup-idea-viable.jpg";
import imgStartupSuccessArijit from "./assets/blog/startup-success-arijit.jpg";
import imgN10X from "./assets/blog/10X.jpg";
import imgThailandYoga from "./assets/blog/Thailand-yoga.jpg";
import imgBliendSchool from "./assets/blog/bliend-school.jpg";
import imgYear2021 from "./assets/blog/Year-2021.jpg";
import imgKolkataBusinessmen from "./assets/blog/kolkata-businessmen.jpg";
import imgKotiTakarBaji from "./assets/blog/koti-takar-baji.jpg";
import imgArijitIndia from "./assets/blog/arijit-India.png";
import imgMentoring from "./assets/blog/mentoring.jpg";
import imgWhatIsEntrepreneurship from "./assets/blog/What-is-Entrepreneurship.jpg";
import imgFear from "./assets/blog/fear.jpg";
import imgThailandShark from "./assets/blog/Thailand-Shark.jpg";
import imgRamnagar from "./assets/blog/ramnagar.jpg";
import imgArijitBhattacharyyaAgarpara from "./assets/blog/Arijit-Bhattacharyya-Agarpara.jpg";
import imgTieconPanel from "./assets/blog/tiecon-panel.jpg";
import imgSundarban from "./assets/blog/sundarban.jpg";
import imgArijitTeamMember from "./assets/blog/Arijit-team-member.png";
import imgTaiwanTravel from "./assets/blog/taiwan-travel.jpg";
import imgInvestment from "./assets/blog/investment.png";
import imgBongEntrepreneurs from "./assets/blog/Bong-Entrepreneurs.jpg";
import imgSaudiArabiaWithLove from "./assets/blog/saudi-arabia-with-love.jpg";
import imgGbgSingapore from "./assets/blog/gbg-singapore.jpg";
import imgArijitSouthKorea from "./assets/blog/Arijit-South_Korea.jpg";
import imgAnimation from "./assets/blog/animation.png";
import imgSingapore from "./assets/blog/Singapore.jpg";
import imgNriStartUpIndia from "./assets/blog/nri-start-up-india.jpg";
import imgSwimmingPool from "./assets/blog/swimming-pool.jpg";
import imgMayanGods from "./assets/blog/mayan-gods.jpg";
import imgLeader from "./assets/blog/leader.png";
import imgLimitlessLife from "./assets/blog/limitless-life.jpg";
import imgSuperheroIndia from "./assets/blog/superhero-India.jpg";
import imgSMELandscape from "./assets/blog/SME-Landscape.jpg";
import imgOrganicFood from "./assets/blog/organic-food.png";
import imgHacker from "./assets/blog/hacker.jpg";
import imgVentureCapitalFirstLP from "./assets/blog/venture-capital-first-LP.jpg";
import imgBusiness from "./assets/blog/business.png";
import imgLeadershipArijit from "./assets/blog/leadership-arijit.jpg";
import imgBGBSSynergyShilpoAbhijan from "./assets/blog/BGBS-Synergy-Shilpo-Abhijan.jpg";
import imgTiEKolkata from "./assets/blog/TiE-Kolkata.jpg";
import imgIncubatorAcclerator from "./assets/blog/incubator-acclerator.png";
import imgBurnOutArijit from "./assets/blog/burn-out-arijit.jpg";
import imgHappy from "./assets/blog/happy.jpg";
import imgBike from "./assets/blog/bike.jpg";
import imgChangingVenture from "./assets/blog/changing-venture.jpg";
import imgMMAUkraine from "./assets/blog/MMA-ukraine.jpg";
import imgCryptoArijitBhattacharyya from "./assets/blog/crypto-arijit-bhattacharyya.jpg";
import imgHarappa from "./assets/blog/harappa.jpg";
import imgMeaningOfLife from "./assets/blog/meaning-of-life.jpg";
import imgSingerThailand from "./assets/blog/singer-thailand.jpg";
import imgMetaverseVR from "./assets/blog/metaverse-VR.jpg";
import imgFool from "./assets/blog/fool.jpg";
import imgNoWorry from "./assets/blog/no-worry.jpg";
import imgThink from "./assets/blog/think.jpg";
import imgTimelessStrategies from "./assets/blog/Timeless-Strategies.jpg";
import imgExitStra from "./assets/blog/exit-stra.jpg";
import imgTypeOfInvestors from "./assets/blog/type-of-investors.jpg";
import imgUnityUnreal from "./assets/blog/unity-unreal.jpg";
import imgBlockchainArijitBhattacharyya from "./assets/blog/blockchain-arijit-bhattacharyya.png";
import imgDefeatBusinessFailure from "./assets/blog/Defeat-Business-Failure.jpg";
import imgRedAngelInvestor from "./assets/blog/red-angel-investor.jpg";
import imgAlphaman from "./assets/blog/Alphaman.jpg";
import imgDAPP from "./assets/blog/DAPP.jpg";
import imgNFTGaming from "./assets/blog/NFT-gaming.jpg";
import imgArijitImmunity from "./assets/blog/arijit-immunity.jpg";
import imgWhatWeDoForWork from "./assets/blog/What-We-Do-For-Work.jpg";
import imgCar from "./assets/blog/car.jpg";
import imgFounderCEO from "./assets/blog/founder&CEO.png";
import imgThreeThings from "./assets/blog/three-things.jpg";
import imgCompetitorGetsFunded from "./assets/blog/Competitor-Gets-Funded.jpg";
import imgSelfWorth from "./assets/blog/self-worth.jpg";

export const archiveImages = {
  "25-popular-science-myths-debunked": imgWorldMyth,
  "8-essential-individuals-all-entrepreneurs-must-have-in-their": imgEntrepreneurshipBengali,
  "ai-in-gaming-innovations-changing-the-future-of-gaming": imgAIGaming,
  "aliens-in-earth": imgAlien,
  "basics-of-making-pitch-deck-for-your-startup": imgPitchDeckForYourStartup,
  "being-entrepreneur-to-build-angel-syndicate-learning": imgLearn,
  "blockage-to-innovation-in-a-company": imgInnovation,
  "blockchain-application-is-not-all-about-crypto": imgBlockchainCrypto,
  "bulgaria-corona-virus-outbreak": imgVirus, // CHECK — matched on "viru"
  "busy-is-not-the-point": imgDonthavetime,
  "capturing-luck": imgLuck,
  "choosing-the-right-employees": imgCEO,
  "climate-change-could-push-bumblebees-to-extinction": imgBombleBee,
  "comparison-of-limited-partnerships": imgLimitedPartnerships,
  "culture-of-india": imgCulture,
  "direct-and-indirect-effects-of-corona-virus-on-the": imgWorldEconomyCoronaVirus,
  "dividing-equity-among-co-founders": imgDividingEquityAmongCoFo,
  "don-t-be-a-selfless-startup": imgStartupEcosystemReset,
  "earth-s-weakening-magnetic-field": imgEarthMagnetic,
  "entrepreneurial-development-and-it-s-impact-on-global-economy": imgEconomyIndia,
  "entrepreneurship-and-regional-development": imgENTREPRENEURSHIPEMPLOYMENT,
  "everything-you-need-to-become-happier-according-to-science": imgArijitBhattacharyyaHappy,
  "fight-against-covid-19": imgVirusCorona,
  "funding-environment-and-what-it-might-mean-for-you": imgCEOFunding,
  "give-away-your-legos-and-other-commandments-for-scaling": imgScalingStartups,
  "gods-and-aliens": imgSpaceTravel,
  "hard-work-vs-long-work": imgHardWork,
  "how-blockchain-is-changing-the-banking-system": imgBlockchainInBanking,
  "how-cosplay-can-adapt-the-look-of-superheroes": imgCosplay,
  "how-do-venture-capitalists-make-money": imgVentureCapital,
  "how-internet-marketplaces-unlock-economic-wealth": imgEconomicTimes,
  "how-often-when-you-prepare-to-speak-anywhere-even": imgArijitPublicSpeaking,
  "how-to-be-successfully-content-with-your-life": imgSuccessfullyContentWithY,
  "how-to-deal-with-success-with-humility": imgStartupSuccess,
  "how-to-define-solopreneur-who-are-they": imgSoloPrenure,
  "how-to-fund-your-startup-things-i-wished-i": imgStartupEcosystem,
  "how-to-know-when-it-s-time-to-give": imgTimeTechnology,
  "how-to-succeed-in-business-strategies-for-entrepreneurs": imgStrategiesForEntrepreneur,
  "impactful-presentation-decks-for-your-startup": imgStartup,
  "important-aztec-gods-and-goddesses-the-top-10-deities": imgAztechGods,
  "international-entrepreneurship-how-to-grow": imgInternationalEntrepreneurs,
  "is-your-startup-idea-viable": imgStartupIdeaViable,
  "keys-to-startup-success": imgStartupSuccessArijit,
  "laws-of-10x-found-everywhere-for-good-reason": imgN10X,
  "life-story-birth-of-yogatraining4u": imgThailandYoga,
  "life-story-blind-kids-connects-more-than-people-who": imgBliendSchool,
  "life-story-come-back-within-a-year-sleeping-for": imgYear2021,
  "life-story-first-office-in-proper-town": imgKolkataBusinessmen,
  "life-story-koti-takar-baji-star-jalsa-cyber-security": imgKotiTakarBaji,
  "life-story-making-india-s-first-epic-based-rpg": imgArijitIndia,
  "life-story-mentoring-in-districts-update-papers-of-a": imgMentoring,
  "life-story-mentoring-in-entrepreneurs-platform-stormy-days-and": imgWhatIsEntrepreneurship,
  "life-story-never-fear-26-nov-2008": imgFear,
  "life-story-no-fear-with-the-person-who-gifted": imgThailandShark,
  "life-story-ramnagar": imgRamnagar,
  "life-story-selling-first-game-and-learning-new-technology": imgArijitBhattacharyyaAgarpara,
  "life-story-sharing-about-digital-human-and-leading-a": imgTieconPanel,
  "life-story-sundarban": imgSundarban,
  "life-story-team-member": imgArijitTeamMember,
  "life-story-the-all-of-a-sudden-friend-from": imgTaiwanTravel,
  "life-story-the-big-event-in-bengal-taking-responsibility": imgInvestment,
  "life-story-the-bong-entrepreneurs": imgBongEntrepreneurs,
  "life-story-the-brother-from-saudi-arabia-2012": imgSaudiArabiaWithLove,
  "life-story-the-google-business-group-2nd-time-in": imgGbgSingapore,
  "life-story-the-korean-expansion-gave-me-a-lifelong": imgArijitSouthKorea,
  "life-story-the-manga-animation-work": imgAnimation,
  "life-story-the-mobile-security-solution-in-singapore-and": imgSingapore,
  "life-story-the-start-up-travel": imgNriStartUpIndia,
  "life-story-the-unknown-woman": imgSwimmingPool,
  "mayan-civilization-gods": imgMayanGods,
  "meaning-of-real-leaders": imgLeader,
  "my-powerful-personal-code-for-a-limitless-life": imgLimitlessLife,
  "need-of-indian-superheros-created-by-virtualinfocom": imgSuperheroIndia,
  "need-of-mentoring-for-startups": imgSMELandscape,
  "need-of-organic-food": imgOrganicFood,
  "one-billion-android-devices-vulnerable-to-hacking-attacks": imgHacker,
  "raising-capital-as-a-first-time-venture-capital-manager": imgVentureCapitalFirstLP,
  "reasons-why-you-need-a-business-coach": imgBusiness,
  "roughness-is-a-quality-of-leadership": imgLeadershipArijit,
  "shilpo-abhijan-in-west-bengal-2013-passion-to-explore": imgBGBSSynergyShilpoAbhijan,
  "slife-story-speaking-in-entrepreneurs-club-while-mother-admitted": imgTiEKolkata,
  "start-up-incubators-vs-accelerators-which-is-best-for": imgIncubatorAcclerator,
  "strategies-to-prevent-leadership-burnouts": imgBurnOutArijit,
  "successfully-content-with-your-life": imgHappy,
  "the-adrenal-rush-of-riding-a-bike": imgBike,
  "the-changing-venture-landscape": imgChangingVenture,
  "the-fight-mma-ukraine": imgMMAUkraine,
  "the-future-banks-or-cryptocurrency": imgCryptoArijitBhattacharyya,
  "the-harrapan-and-mohenjo-daro-civilizations-were-more-advanced": imgHarappa,
  "the-meaning-of-life": imgMeaningOfLife,
  "the-pop-singer-from-uk-few-celeb-models": imgSingerThailand,
  "the-rise-of-metaverse": imgMetaverseVR,
  "the-willingness-to-be-a-fool": imgFool,
  "there-s-no-need-to-panic-and-figure-out": imgNoWorry,
  "think": imgThink,
  "timeless-strategies-that-drive-successful-entrepreneurship": imgTimelessStrategies,
  "types-of-exit-strategies": imgExitStra,
  "types-of-investors-is-all-you-need-to-know": imgTypeOfInvestors,
  "unity-or-unreal-which-one-you-can-choose-for": imgUnityUnreal,
  "use-cases-of-blockchain-in-banking": imgBlockchainArijitBhattacharyya,
  "ways-to-defeat-business-failure-and-flourish-in-hard": imgDefeatBusinessFailure,
  "what-are-the-red-flags-for-an-angel-investor": imgRedAngelInvestor,
  "what-do-you-mean-by-alpha-man": imgAlphaman,
  "what-is-a-dapp": imgDAPP,
  "what-is-nfts-and-will-nfts-non-fungible-tokens": imgNFTGaming,
  "what-is-virus-can-you-kill-virus-why-corona": imgArijitImmunity,
  "what-to-do-after-feeling-miserable-and-worthless-at": imgWhatWeDoForWork,
  "who-is-responsible-when-a-self-driving-car-kills": imgCar,
  "why-every-founder-of-a-company-is-a-superhero": imgFounderCEO,
  "you-can-have-two-big-things-but-not-three": imgThreeThings,
  "your-competitor-gets-funded-and-you-are-not-what": imgCompetitorGetsFunded,
  "your-real-work-as-ceo-is-to-infuse-top": imgSelfWorth,
};

// Posts with no picture yet (35):
//   self-worth-is-not-the-same-as-net-worth
//   year-review-2021
//   can-an-ai-driven-app-check-if-you-re
//   you-will-make-all-major-decisions-after-fundraising-and
//   italy-may-consider-lockdown-of-lombardy-region-in-response
//   is-the-current-slowdown-in-indian-economy-cyclical-or
//   steps-to-find-your-purpose-when-life-is-crashing
//   getting-inside-your-buyer-s-head
//   the-fundamental-lesson-of-the-forces-governing-scaling-startups
//   how-do-we-attract-more-women-in-women-tech
//   how-nft-is-disrupting-the-market
//   how-to-be-great-at-failing
//   how-to-become-insanely-well-connected
//   life-story-bengal-s-first-cosplay-show-entering-into
//   life-story-partnership
//   life-story-investment-opportunity
//   life-story-human-trafficking
//   life-story-the-jungle-the-kids-and-the-smile
//   life-story-one
//   the-next-decade-in-ai
//   how-to-overcome-anger-to-be-better-for-family
//   recognizing-and-overcoming-the-fears-that-make-us-settle
//   scientists-turn-frog-cells-into-tiny-living-robots-that
//   serial-entrepreneurs-versus-first-time-entrepreneurs
//   startup-the-team-you-need-if-you-want-to
//   the-critical-startup-skills-you-might-be-overlooking-and
//   the-critical-startup-skills-you-might-be-overlooking
//   the-modern-business-plan
//   the-resetting-of-the-startup-industry
//   time-travel-in-mahabharata
//   it-s-time-to-wake-up-and-unfold-the
//   life-story-the-unknown-woman-2
//   tribes-and-races-who-are-more-developed-than-humans
//   what-do-we-learn-from-snake
//   what-is-entrepreneurship

// Pictures not used by any post (51):
//   1.jpg
//   2.jpg
//   3412699.jpg
//   8-indie.jpg
//   Agartala-CM.jpg
//   Arijit-Bhattacharya-China.jpg
//   Arijit-Bhattacharya-xian.jpg
//   arijit-bhattacharyya-gym.jpg
//   arijit-bhattacharyya.jpg
//   Arijit-life-story.jpg
//   arijit-life.jpg
//   arijit-medical.png
//   Arijit_Bhattacharjee.jpg
//   arijit_bhattacharyya.png
//   augmented-reality-glass.png
//   crypto.png
//   Elena_Lobova.jpg
//   entrep-international.png
//   food.jpg
//   give-away.jpg
//   gym-arijit.jpg
//   hanuman.png
//   happy-room.jpg
//   itc.jpg
//   Japan.jpg
//   Jenny.png
//   Krishnanagar.jpg
//   leadership.jpg
//   life.jpg
//   malbazar.jpg
//   manga-Arijit.jpg
//   metaverse.jpg
//   mixed-reality.png
//   mumbai-arijit-bhattacharyya.png
//   NEN-Arijit.jpg
//   paolo-amba.jpg
//   public-speaker.jpg
//   public-speaking.jpg
//   Rishav.jpg
//   saltlake.jpg
//   Srijla.jpg
//   SRM-University.jpg
//   success.jpg
//   super-heros.jpg
//   superhero.jpg
//   teacher.png
//   techno_VR.jpg
//   tiger-lilly.jpg
//   tinni-bhattacharyya.png
//   trust.jpg
//   we-are.jpg
