// Press, broadcast and speaking archive appended to the "National & Business
// Media" clippings board.
//
// `img` is a path under src/assets, resolved by PressImage's glob lookup.
// Images come from src/assets/Pressnews; files already pinned to the board or
// used elsewhere on the page are avoided, except where a caption's only true
// match was one of those (Josh Talk, TED X, The Hindu).

export const pressArchive = [
  { t: "Star entrepreneur award", img: "Pressnews/star.jpg", tilt: -3 },
  { t: "Press news about Arijit in Economic Times", img: "Pressnews/Arijit-Bhattacharyya-ECONOMICS.jpg", tilt: 2.5 },
  { t: "Anandabazar — 8th Dec 2024", img: "Pressnews/2024/anandabazar-B.jpg", tilt: 1.5 },
  { t: "TV9 Bengali — game development & VR", img: "Pressnews/2021/TV9.jpg", tilt: -2 },
  { t: "Diplomatic World 65", img: "Pressnews/2021/65.jpg", tilt: 3 },
  { t: "Speaker in Vibrant Saurashtra, Rajkot", img: "Pressnews/vibrant-gujarat.jpg", tilt: -1.5 },
  { t: "Award from the Education Minister of Bengal", img: "Pressnews/Arijit_Bhattacharya_vic.jpg", tilt: 2 },
  { t: "Speaking on the growth of VR on Taaza TV", img: "Pressnews/Arijit-Taza-tv.jpg", tilt: -3 },
  { t: "Times of India — 7th Dec 2024", img: "Pressnews/2024/timesofindia-s.jpg", tilt: 2.5 },
  { t: "Bengal's first entrepreneurship event", img: "Pressnews/bengal-growth.jpg", tilt: 1.5 },
  { t: "Talk in CNBC", img: "Pressnews/latest-speaks/cnbc.jpg", tilt: -2 },
  { t: "Keynote speaker in Business World", img: "Pressnews/arijit-bhattacharyya_business-world.jpg", tilt: 3 },
  { t: "Talking on next-gen e-commerce applications", img: "Pressnews/2018/quiker.jpg", tilt: -1.5 },
  { t: "TV interview on the Blue Whale game", img: "Pressnews/Blue_Whale_Challange.jpg", tilt: 2 },
  { t: "Agartala panel talk on growth", img: "Pressnews/agartala.jpg", tilt: -3 },
  { t: "China film festival", img: "Pressnews/china-films.jpg", tilt: 2.5 },
  { t: "Hindustan Times", img: "Pressnews/hindustan-times-startup.jpg", tilt: 1.5 },
  { t: "How angel investment works", img: "Pressnews/angel.jpg", tilt: -2 },
  { t: "Good Morning Nepal", img: "Pressnews/Arijit_Nepal.jpg", tilt: 3 },
  { t: "NAB China", img: "Pressnews/latest-speaks/virtual-reality-china.jpg", tilt: -1.5 },
  { t: "Invest Odisha", img: "Pressnews/odisha.jpg", tilt: 2 },
  { t: "Game with Subhashree Ganguly", img: "Pressnews/Subhasree_Arijit.jpg", tilt: -3 },
  { t: "NEN", img: "Pressnews/nen.jpg", tilt: 2.5 },
  { t: "Nepal", img: "Pressnews/latest-speaks/nepal.jpg", tilt: 1.5 },
  { t: "ICC Startuppad", img: "Pressnews/ICC_Startup_Pad.jpg", tilt: -2 },
  { t: "Ebela newspaper", img: "Pressnews/2018/MOMO-ebela_news.jpg", tilt: 3 },
  { t: "Kantipur Media", img: "Pressnews/2018/kantipur_media.jpg", tilt: -1.5 },
  { t: "Nepal newspaper", img: "Pressnews/2018/nepal_news.jpg", tilt: 2 },
  { t: "Invest Finland & India", img: "Pressnews/latest-speaks/finland.jpg", tilt: -3 },
  { t: "IAMAI", img: "Pressnews/2018/IAMAI.jpg", tilt: 2.5 },
  { t: "Talk on products", img: "Pressnews/latest-speaks/products.jpg", tilt: 1.5 },
  { t: "ICC Startuppad 2018", img: "Pressnews/arijit_startup_pad.jpg", tilt: -2 },
  { t: "Economic Times", img: "Pressnews/arijit-news.jpg", tilt: 3 },
  { t: "Skilling for jobs — edtech", img: "Pressnews/2018/edtech-2018.png", tilt: -1.5 },
  { t: "Smart city projects opportunity", img: "Pressnews/latest-speaks/smart-city.jpg", tilt: 2 },
  { t: "GATO 1.0", img: "Pressnews/2019/GATO-vr-ar-gaming.png", tilt: -3 },
  { t: "USA Consulate office talk on startups", img: "Pressnews/2018/ICC_Startupad_American_Center-Arijit.jpg", tilt: 2.5 },
  { t: "Indian IOT", img: "Pressnews/infocom.jpg", tilt: 1.5 },
  { t: "IEEE — money on the table", img: "Pressnews/2018/IEEE-money-on-table.jpg", tilt: -2 },
  { t: "Josh Talk", img: "Pressnews/2018/Josh-Talk_Bengali.jpg", tilt: 3 },
  { t: "Nepal TV", img: "Pressnews/2018/kantipur_TV.jpg", tilt: -1.5 },
  { t: "Economic forum", img: "Pressnews/assocham.jpg", tilt: 2 },
  { t: "Startup Himachal", img: "Pressnews/2018/Shimla.jpg", tilt: -3 },
  { t: "Startup Thailand", img: "Pressnews/latest-speaks/startup.jpg", tilt: 2.5 },
  { t: "TiEcon Punjab", img: "Pressnews/2018/tiecon_punjab.jpg", tilt: 1.5 },
  { t: "Nepal", img: "Pressnews/Arijit_Bhattacharyya_Nepal.png", tilt: -2 },
  { t: "Mrs India", img: "Pressnews/2018/Mrs_India.jpg", tilt: 3 },
  { t: "Startup Nordic", img: "Pressnews/investment.jpg", tilt: -1.5 },
  { t: "Future of AR & VR", img: "Pressnews/2019/virtual-reality.png", tilt: 2 },
  { t: "Award for best casual game", img: "Pressnews/2019/game-development.png", tilt: -3 },
  { t: "With Prosenjit Chatterjee", img: "Pressnews/Prosenjit_Chakraborty.jpg", tilt: 2.5 },
  { t: "Own cosplay show — Indian cosplay", img: "Pressnews/cosplay.jpg", tilt: 1.5 },
  { t: "Keynote speaker", img: "Pressnews/latest-speaks/keynote.jpg", tilt: -2 },
  { t: "GBG Singapore", img: "Pressnews/Google_Business_group.jpg", tilt: 3 },
  { t: "South Korea business development", img: "Pressnews/south_Korea_game.jpg", tilt: -1.5 },
  { t: "Rotary Kolkata", img: "Pressnews/rotary_kolkata.jpg", tilt: 2 },
  { t: "Modelling", img: "Pressnews/Srijla_Guha.jpg", tilt: -3 },
  { t: "Interview of Miss India Universe", img: "Pressnews/miss-india.jpg", tilt: 2.5 },
  { t: "MSME mentoring", img: "Pressnews/finance-clinic.jpg", tilt: 1.5 },
  { t: "Startup Jharkhand", img: "Pressnews/jharkhand.jpg", tilt: -2 },
  { t: "Talk on IP & business", img: "Pressnews/arijit-commerce.jpg", tilt: 3 },
  { t: "Book publish — Kolkata blogger", img: "Pressnews/blogger-kolkata.jpg", tilt: -1.5 },
  { t: "While making short movies", img: "Pressnews/Ramoji_Films.jpg", tilt: 2 },
  { t: "Xian film festival as a speaker", img: "Pressnews/arijit_bhattacharyya-films.jpg", tilt: -3 },
  { t: "Future of VR", img: "Pressnews/virtual_reality.jpg", tilt: 2.5 },
  { t: "Mr Khanna while making the Shaktimaan game", img: "Pressnews/im_superhero.jpg", tilt: 1.5 },
  { t: "Mr Yasuhiro Fukushima, founder of Square Enix", img: "Pressnews/japan.jpg", tilt: -2 },
  { t: "Actor Jeet while making the Boss 2 game", img: "Pressnews/Jeet_Arijit_Bhattacharyya.jpg", tilt: 3 },
  { t: "Making Bollywood actor based games — Raaz 2", img: "Pressnews/raaz_2.jpg", tilt: -1.5 },
  { t: "NEN mentoring", img: "Pressnews/NEN_kolkata.jpg", tilt: 2 },
  { t: "Panel with the founder of Century Ply", img: "Pressnews/century_ply.jpg", tilt: -3 },
  { t: "Talk on cyber security", img: "Pressnews/cyber_security.jpg", tilt: 2.5 },
  { t: "Star Wars story", img: "Pressnews/Star_Wars.jpg", tilt: 1.5 },
  { t: "Paoli Dam film festival", img: "Pressnews/paoli_dam.jpg", tilt: -2 },
  { t: "Parambrata", img: "Pressnews/Parambrata_Arijit.jpg", tilt: 3 },
  { t: "The game talk with Dev", img: "Pressnews/Dev_Arijit.jpg", tilt: -1.5 },
  { t: "MSME Govt Bengal mentoring session", img: "Pressnews/murshidabad.jpg", tilt: 2 },
  { t: "IIT KGP GES", img: "Pressnews/IIT-Kharagpur.jpg", tilt: -3 },
  { t: "Short film festival Kolkata", img: "Pressnews/2019/short-film-festival-kolkata.jpg", tilt: 2.5 },
  { t: "Data security — Rotary talk", img: "Pressnews/2019/rotary.jpg", tilt: 1.5 },
  { t: "Startup mentoring NIT", img: "Pressnews/2019/NIT-startup.jpg", tilt: -2 },
  { t: "Invest Jharkhand — Anandabazar", img: "Pressnews/ABP_Arijit.jpg", tilt: 3 },
  { t: "FICCI Frames VR panel moderator", img: "Pressnews/2019/ficci.jpg", tilt: -1.5 },
  { t: "Program moderator — NRI Startup India", img: "Pressnews/2019/NRI-startup_tie-delhi.jpg", tilt: 2 },
  { t: "Children film festival", img: "Pressnews/latest-speaks/animation.jpg", tilt: -3 },
  { t: "TED X Talk", img: "Pressnews/2019/tedx.jpg", tilt: 2.5 },
  { t: "VR workshop", img: "Pressnews/2019/virtual-reality.jpg", tilt: 1.5 },
  { t: "AI, ML and VR workshop in MDI", img: "Pressnews/2019/mdi.jpg", tilt: -2 },
  { t: "Swimming with Investors — IIFT", img: "Pressnews/2019/business-plan.png", tilt: 3 },
  { t: "Anandabazar", img: "Pressnews/2020/anandabazar-abp.jpg", tilt: -1.5 },
  { t: "ICC Startup 2019", img: "Pressnews/2019/ICC.jpg", tilt: 2 },
  { t: "St Xavier's College", img: "Pressnews/2019/xaviour.jpg", tilt: -3 },
  { t: "DD Bangla TV — Career Plus", img: "Pressnews/latest-speaks/DD_bangla.jpg", tilt: 2.5 },
  { t: "Blockchain talk Bangkok", img: "Pressnews/2019/blockchain.jpg", tilt: 1.5 },
  { t: "NIT Raipur India", img: "Pressnews/2019/raipur-NIT.jpg", tilt: -2 },
  { t: "HULT Prize as judge", img: "Pressnews/2019/HULT-Kolkata.jpg", tilt: 3 },
  { t: "NIT Silchar keynote", img: "Pressnews/2019/NIT-Silchar-startup.jpg", tilt: -1.5 },
  { t: "ASK Circle 2019", img: "Pressnews/2019/ask-circle.jpg", tilt: 2 },
  { t: "Data science keynote", img: "Pressnews/2019/data-science.jpg", tilt: -3 },
  { t: "IIM Calcutta business plan judge", img: "Pressnews/2019/IIMC.png", tilt: 2.5 },
  { t: "The Hindu", img: "Pressnews/2019/the-hindu.png", tilt: 1.5 },
  { t: "Calcutta Chamber of Commerce", img: "Pressnews/2020/calcutta-chamber-of-commerce.jpg", tilt: -2 },
  { t: "Steve Waugh, Kolkata", img: "Pressnews/2020/Arijit-Steve.jpg", tilt: 3 },
  { t: "Let's Start", img: "Pressnews/2020/lets-start.jpg", tilt: -1.5 },
  { t: "Axis Bank keynote speaker", img: "Pressnews/2020/axis-bank-spk.jpg", tilt: 2 },
  { t: "World Leadership Conference", img: "Pressnews/2020/World-Leadership-Conference.jpg", tilt: -3 },
  { t: "World Leadership Conference", img: "Pressnews/2020/World-Leadership-Conference-Arijit.jpg", tilt: 2.5 },
  { t: "Media Next — Anandabazar", img: "Pressnews/2021/magazine-news-1.jpg", tilt: 1.5 },
  { t: "India Real on virtual reality", img: "Pressnews/2020/indiareal.jpg", tilt: -2 },
  { t: "Diplomatic World", img: "Pressnews/2021/diplomatic-world.jpg", tilt: 3 },
  { t: "Aajkal — virtual reality", img: "Pressnews/2020/aajkal.jpg", tilt: -1.5 },
];
